baseURL = 'https://ortizma.com/'
languageCode = 'en-us'
title = 'Pablo Ortiz López'
theme = 'stack'
paginate = 5
hasCJKLanguage = false

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages]
[languages.en]
contentDir = 'content'
languageCode = 'en'
languageDirection = 'ltr'
languageName = 'English'
title = 'Pablo Ortiz López'
weight = 1
[languages.en.params]
subtitle = 'Personal Blog'
[languages.en.params.sidebar]
subtitle = "This webpage serves both as a place to document my engineering projects, as well as a way to practice the essential skill of sharing knowledge."
[languages.es]
contentDir = 'content'
languageCode = 'es'
languageDirection = 'ltr'
languageName = 'Español'
title = 'Pablo Ortiz López'
weight = 1
[languages.es.params]
subtitle = 'Blog Personal'
[languages.es.params.sidebar]
subtitle = "Esta página sirve tanto para documentar mis proyectos de ingeniería, como para practicar la habilidad esencial de compartir el conocimiento."
